name: Server Workflow

on:
  push:
    branches: [main]
    # paths: [server/**]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh into server, pull changes and re-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo su
            cd auto
            git -C ${{ github.event.repository.name }} pull || git clone ${{ env.GITHUB_ACTION_REPOSITORY }} ${{ github.event.repository.name }}
            cd ${{ github.event.repository.name }}/server
            docker-compose up -d --build
